steps:
  install:
    image: madnificent/ember:4.12.1-node_18
    commands:
      - npm ci
  lint-js:
    image: madnificent/ember:4.12.1-node_18
    depends_on: [install]
    commands:
      - npm run lint:js
  lint-hbs:
    image: madnificent/ember:4.12.1-node_18
    depends_on: [install]
    commands:
      - npm run lint:hbs
when:
  - event: pull_request
